services:
 - docker

language: "perl"
sudo: true
# travis-perl filters out cperl, perlbrew does support it
perl:
  # need perl 5.22 or later - currently using 5.22 in production
  - "5.22"
  # - "5.26"
  # - "5.28"
  # - "5.30"
  # - "dev"
  # - "blead"

env:
  global:
     # Carton --deployment only works on the same version of perl
     # that the snapshot was built from.
     - DEPLOYMENT_PERL_VERSION=5.22
     - DEVEL_COVER_OPTIONS="-ignore,^local/"
     - PERL_CARTON_PATH=$TRAVIS_BUILD_DIR/local
     - CPAN_RESOLVER=snapshot
     - AUTOMATED_TESTING=1
     - HARNESS_TIMER=1
     - AUTHOR_TESTING=0
     - RELEASE_TESTING=0
     - COVERAGE=1
     - DOCKER_IMAGE_NAME=metacpan-grep-front-end
# matrix:

before_install:
  - mkdir /home/travis/bin || true
  - ln -s `which true` /home/travis/bin/cpansign
  - eval $(curl https://travis-perl.github.io/init) --auto
  - git clone https://github.com/atoomic/metacpan-extracted-lite.git ../metacpan-cpan-extracted-lite # get a minimal git repo
  - cpanm -n App::cpm Carton::Snapshot
  - cpm install -g --without-test Test2::Bundle::Extended Test2::Tools::Explain Test2::Plugin::NoWarnings

install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled
  - cpm install -g --without-test --cpanfile cpanfile

before_script:
  - coverage-setup

after_success:
  - coverage-report
  - deploy/build.sh

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  fast_finish: true
  allow_failures:
    - env: COVERAGE=1 AUTHOR_TESTING=1
    - perl: "blead"

# Hack to not run on tag pushes:
branches:
  except:
  - /^v?[0-9]+\.[0-9]+/
