blank_issues_enabled: false
contact_links:
  - name: 💬 Community Support
    url: //github.com/metacpan/metacpan-grep-front-end/discussions/
    about: Please use GitHub Discussions for questions and support.
